---
title: "Developing Data Products Asst 1"
author: "Yasneen Ashroff"
date: "October 16, 2016"
output: 
    html_document: 
        keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Crime Rates in American cities

This data was sourced from https://data.cityofnewyork.us.

```{r, echo=FALSE , warning=FALSE,message=FALSE}
library(leaflet)
library(dplyr)
df<-read.csv(url("https://data.cityofnewyork.us/api/views/3h6b-pt5u/rows.csv?accessType=DOWNLOAD"))
```
```{r echo=TRUE}
df
```

```{r, echo=FALSE, results="hide",warning=FALSE,message=FALSE}
df$lat<-c(40.7128, 37.3382, 32.7157, 34.0522, 36.1699, 33.4484, 39.9526, 32.7767, 29.7604, 29.4241)
df$lng<-c(-74.0059, -121.8863, -117.1611, -118.2437, -115.1398, -112.0740, -75.1652, -96.7970, -95.3698, -98.4936)
df$city_rate<-paste(df$City,df$Rate)
```
```{r, warning=FALSE , message=FALSE}
df %>% leaflet() %>% addTiles() %>% addCircles(weight=1,radius=(df$Rate)*20,popup=df$city_rate)
```
